apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      name: prometheus
    spec:
      containers:
        - name: prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.retention=1d
          image: prom/prometheus
          ports:
            - containerPort: 9090
              name: web
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      securityContext:
        runAsUser: 0
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 420
            name: prometheus
