apiVersion: v1
kind: Namespace
metadata:
  name: flux
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=flux
            - --git-path=minikube
            - --git-user=ribbybibby
            - --git-email=ribbybibby@users.noreply.github.com
            - --git-url=git@github.com:ribbybibby/kubernetes
