global:
  scrape_interval: 1m

scrape_configs:
  - job_name: ssl-exporter
    metrics_path: /probe
    static_configs:
      - targets:
          - kubernetes.default.svc:443
          - google.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ssl-exporter:9219
