# project for applying cluster objects
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  sourceRepos:
    - "https://github.com/ribbybibby/kubernetes"
---
# only namespaced objects
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: namespaced
spec:
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  sourceRepos:
    - "https://github.com/ribbybibby/kubernetes"
